export declare const BLUE_1 = "#94c1ff";
export declare const BLUE_2 = "#588bee";
export declare const BLUE_3 = "#005ab6";
export declare const GREEN_1 = "#17c28f";
export declare const GREEN_2 = "#46dfaa";
export declare const GREEN_3 = "#008c5d";
export declare const YELLOW_1 = "#ffd45f";
export declare const YELLOW_2 = "#fdb844";
export declare const YELLOW_3 = "#c08300";
export declare const RED_1 = "#ff988b";
export declare const RED_2 = "#ee6159";
export declare const RED_3 = "#b0272b";
export declare const LIGHT_BLUE_1 = "#5de3ff";
export declare const LIGHT_BLUE_2 = "#37c7e6";
export declare const LIGHT_BLUE_3 = "#0091af";
export declare const PINK_1 = "#ff8ac9";
export declare const PINK_2 = "#de5193";
export declare const PINK_3 = "#a30861";
export declare const LIME_1 = "#9df26a";
export declare const LIME_2 = "#81d54f";
export declare const LIME_3 = "#489e10";
export declare const PURPLE_1 = "#e495ff";
export declare const PURPLE_2 = "#aa60e2";
export declare const PURPLE_3 = "#732caa";
export declare const COLORS_SMALL: string[];
export declare const COLORS_MIDDLE: string[];
export declare const COLORS_LARGE: string[];
